"""Export rows that resolve a RogueLike Select node.

A Select node - the repair station - offers three choices. The client rolls
them locally in `setEvent`/`makeRandomExport` and never tells the gateway
which three it drew: `RogueLike_Trigger_Export_Select` clears
`Event.LocationExports` and identifies the pick only by setting
`NowToyTops[<chosen top>].Buffs = [ExportItemId]`.

So the gateway resolves the choice the same way the client does, through
`data/RogueLikeExport`: `RewardType` says whether the pick repairs the top or
grants a chip, and `ExportNum` says by how much. The prologue declares exactly
three Select rows and their item ids are distinct, so the single id the
client sends is enough to name the choice.

The table is generated by ``tools/extract_roguelike_exports.py`` and committed
rather than parsed at runtime, because the resource is an untracked
preservation input and a clean checkout has to run without it.
``server/tests/test_roguelike_exports.py`` regenerates it from the artifact
when one is present, so drift is caught rather than assumed away.
"""

from __future__ import annotations

from dataclasses import dataclass

from app.protocol.roguelike_events import (
    PROLOGUE_CHAPTER_ID,
    REWARD_EVENT,
    SELECT_EVENT,
)

# RogueLikeExport_ERewardType, from the decrypted bundle.
ITEM_REWARD = 1
CHIJI_ITEM_REWARD = 2
RECOVER_HP_REWARD = 3

# An export row is filed under the node kind it can appear on.
SELECT_EVENT_TYPE = SELECT_EVENT
REWARD_EVENT_TYPE = REWARD_EVENT

__all__ = [
    "CHIJI_ITEM_REWARD",
    "ITEM_REWARD",
    "PROLOGUE_CHAPTER_ID",
    "PROLOGUE_SELECT_EXPORTS",
    "PROLOGUE_REWARD_EXPORTS",
    "RECOVER_HP_REWARD",
    "REVIVE_DIVISOR",
    "REWARD_EVENT_TYPE",
    "RogueLikeExport",
    "SELECT_EVENT_TYPE",
    "reward_export",
    "select_export",
]

# A defeated top cannot be repaired outright: onBtnConfirm warns first and
# then restores half the row's percentage.
REVIVE_DIVISOR = 2


@dataclass(frozen=True)
class RogueLikeExport:
    export_key: int
    export_item_id: int
    reward_type: int
    export_num: int


# data/RogueLikeExport, BelongChapter == -1 and EventType == SelectEvent.
PROLOGUE_SELECT_EXPORTS: dict[int, RogueLikeExport] = {
    1: RogueLikeExport(100020, 1, RECOVER_HP_REWARD, 40),
    4301: RogueLikeExport(100018, 4301, CHIJI_ITEM_REWARD, 1),
    4302: RogueLikeExport(100019, 4302, CHIJI_ITEM_REWARD, 1),
}


# data/RogueLikeExport, BelongChapter == -1 and EventType == RewardEvent.
# A reward chest confirms with the export keys it was entered with rather
# than an item id, so this table is indexed the other way round.
PROLOGUE_REWARD_EXPORTS: dict[int, RogueLikeExport] = {
    100021: RogueLikeExport(100021, 2028, ITEM_REWARD, 2),
    100022: RogueLikeExport(100022, 2004, ITEM_REWARD, 2),
    100023: RogueLikeExport(100023, 1227894833, ITEM_REWARD, 500),
}


def select_export(export_item_id: int) -> RogueLikeExport | None:
    """Resolve the item id a Select confirm carries, or None if undeclared."""
    return PROLOGUE_SELECT_EXPORTS.get(export_item_id)


def reward_export(export_key: int) -> RogueLikeExport | None:
    """Resolve an export key a reward node carries, or None if undeclared."""
    return PROLOGUE_REWARD_EXPORTS.get(export_key)
