#!/usr/bin/env python3
from pathlib import Path
import re, json

ROOT = Path(__file__).resolve().parents[1]
TARGETS = ["intl_base/assets", "intl_assets/assets", "cn_apk/assets"]
CJK_RE = re.compile(r"[\u4e00-\u9fff]{1,}")
PRIORITY = re.compile(r"login|server|notice|main|settings|project|resources|import/0|登录|服务器|公告|开始|加载", re.I)

def is_probably_text(data: bytes) -> bool:
    if b'\x00' in data[:4096]:
        return False
    try:
        data[:4096].decode('utf-8')
        return True
    except UnicodeDecodeError:
        return False

def snippets(text: str):
    hits=[]
    for m in CJK_RE.finditer(text):
        start=max(0,m.start()-50); end=min(len(text),m.end()+80)
        s=text[start:end].replace('\n',' ').replace('\r',' ')
        hits.append(s)
        if len(hits)>=5:
            break
    return hits

def main():
    rows=[]
    for target in TARGETS:
        base=ROOT/target
        if not base.exists():
            continue
        for p in base.rglob('*'):
            if not p.is_file() or p.stat().st_size>5_000_000:
                continue
            try: data=p.read_bytes()
            except Exception: continue
            if not is_probably_text(data):
                continue
            text=data.decode('utf-8','ignore')
            count=len(CJK_RE.findall(text))
            if count:
                rel=str(p.relative_to(ROOT))
                score=count + (1000 if PRIORITY.search(rel+text[:1000]) else 0)
                rows.append((score,count,rel,snippets(text)))
    rows.sort(reverse=True)
    out=ROOT/'docs/ENGLISH_LOCALIZATION_NOTES.md'
    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open('w',encoding='utf-8') as f:
        f.write('# English Localization Notes\n\n')
        f.write('Generated by `tools/extract_cjk_strings.py`. This is a triage list, not a complete translation. Prioritize visible login/server/lobby/tutorial strings and backend-controlled messages.\n\n')
        f.write('## Strategy\n\n')
        f.write('- Use the international client as the player-facing base.\n')
        f.write('- Supply server-side text in English from `server/app/data/en/*.json`.\n')
        f.write('- Translate hardcoded client text only after it is seen in runtime screenshots/logs.\n')
        f.write('- Do not blindly machine-translate all asset dumps.\n\n')
        f.write('## CJK candidate files\n\n')
        for score,count,rel,snips in rows[:250]:
            f.write(f'### `{rel}` — {count} CJK runs\n\n')
            for s in snips:
                f.write(f'- `{s[:500]}`\n')
            f.write('\n')
        if len(rows)>250:
            f.write(f'\n_Only top 250 files shown out of {len(rows)} candidate files._\n')
    print(out)
    print(f'{len(rows)} files with CJK text')

if __name__ == '__main__':
    main()
